package ru.rdude.rpg.game.logic.enums;

public enum Target {NO, SELF, ALLY, ENEMY, ANY, ALL, ALL_ALLIES, ALL_ENEMIES, RANDOM_ALLY, RANDOM_ENEMY, RANDOM_ANY,
    LEFT_FROM_TARGET, RIGHT_FROM_TARGET, LEFT_ALLY, RIGHT_ALLY}
